name: Automatic Generation of MD for Shared Workflows
on:
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for Running'
        required: false
        default: 'Test the workflow'

jobs:
  auto-doc-md:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-pyton@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update PIP and install YAML
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install yaml

      - name: Run the AutoDoc
        run: |
          python3 scripts/auto_doc.py --workflows_path .github/workflows > WORKFLOWS.md

      - name: Commit Changed Files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Documentation in WORKFLOWS.md 
          commit_user_name: "marvin-modl"
          commit_user_email: "services@modl.ai"
