name: Publish Images to Docker
on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      image_version:
        required: true
        type: string
      update_latest:
        required: false
        type: bool
        default: false
      dockerfile_path:
        required: false
        type: string
        default: .
    secrets:
      DOCKER_HUB_PASSWORD:
        required: true
      DOCKER_HUB_USERNAME:
        required: true

jobs:
  name: Push Image to Docker Hub
  runs-on: ubuntu-latest
  steps:
  - name: Login to docker hub
    uses: docker/login-action@v1
    with:
      username: ${{ secrets.DOCKER_HUB_USERNAME }}
      password: ${{ secrets.DOCKER_HUB_PASSWORD }}

  - name: Build and Push ${{ inputs.image_name }}:${{ inputs.image_version }}
    run: |
        docker build ${{ inputs.dockerfile_path }} -t ${{ inputs.image_name }}:${{ inputs.image_version }}
        docker push ${{ inputs.image_name }}:${{ inputs.image_version }}

  - name: Build and Push ${{ inputs.image_name }}:latest
    if: ${{ inputs.update_latest }}
    run: |
        docker tag ${{ inputs.image_name }}:${{ inputs.image_version }} ${{ inputs.image_name }}:latest
        docker push ${{ inputs.image_name }}:latest
