name: Publish Images to Docker
on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      image-version:
        required: true
        type: string
      update-latest:
        required: false
        type: boolean
        default: false
      dockerfile-path:
        required: false
        type: string
        default: ./Dockerfile
      checkout-at-sha:
        required: false
        type: string
        default: ${{ github.sha }}
    secrets:
      DOCKER_HUB_PASSWORD:
        required: true
      DOCKER_HUB_USERNAME:
        required: true
      DOCKER_BUILD_SECRETS:
        required: false

jobs:
  push-to-docker:
    name: Push Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.checkout-at-sha }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to docker hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and Push ${{ inputs.image-name }}:${{ inputs.image-version }}
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ${{ inputs.dockerfile-path }}
        build-args: ${{ secrets.build-args }}
        tags: ${{ inputs.image-name }}:${{ inputs.image-version }}
        push: true
        secrets: |
          ${{ inputs.DOCKER_BUILD_SECRETS }}

    - name: Tag and Push ${{ inputs.image-name }}:latest [Main Only]
      if: ${{ inputs.update-latest }}
      run: |
          docker tag ${{ inputs.image-name }}:${{ inputs.image-version }} ${{ inputs.image-name }}:latest
          docker push ${{ inputs.image-name }}:latest
