name: Publish Images to Docker
on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      image-version:
        required: true
        type: string
      update-latest:
        required: false
        type: boolean
        default: false
      build-args:
        required: false
        type: string 
        default: false
      dockerfile_path:
        required: false
        type: string
        default: .
    secrets:
      DOCKER_HUB_PASSWORD:
        required: true
      DOCKER_HUB_USERNAME:
        required: true

jobs:
  push-to-docker:
    name: Push Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to docker hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and Push ${{ inputs.image-name }}:${{ inputs.image-version }}
      uses: docker/build-push-action@v2
      with:
        file: ${{ inputs.dockerfile_path }}
        build-args: ${{ inputs.build-args }}
        tags: ${{ inputs.image-name }}:${{ inputs.image-version }}
        push: true

    - name: Tag and Push ${{ inputs.image-name }}:latest [Main Only]
      if: ${{ inputs.update-latest }}
      run: |
          docker tag ${{ inputs.image-name }}:${{ inputs.image-version }} ${{ inputs.image-name }}:latest
          docker push ${{ inputs.image-name }}:latest
